# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "v1.5.0" ]
  pull_request:
    branches: [ "main", "v1.5.0" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install ncbi-blast+ clustalw -y
        sudo apt-get install python3-pip python3-numpy python3-pandas -y
        python3 -m pip install --upgrade pip setuptools
        pip3 install pytest "biopython>=1.7,<1.78"
        pip3 install -e .
    - name: Test  with pytest
      run: |
        pytest -o log_cli=true --basetemp=tmp-pytest
